"""A daily or weekly AI-written fleet health summary — "what changed, what
needs attention" in plain language, generated unattended by
`app.tasks.ai_jobs.generate_fleet_summary` and shown on the Dashboard.

Deliberately display-only for now: nothing here sends an email, a Slack
message, or any other notification — see that task's own module docstring
for why, and `AppSettings.fleet_summary_frequency` for the opt-in switch
(off by default, since this is a genuine AI API call with a genuine token
cost, unlike the always-on daily `FleetSnapshot` row).

One row per generated summary (not a singleton overwritten in place) so
the Dashboard can eventually show "what changed" against last time — kept
bounded the same way `FleetSnapshot`/`MachineUpdateRun` are, via
`fleet_summary_retention_days` and a daily purge job.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class FleetSummary(Base):
    __tablename__ = "fleet_summaries"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)

    # "daily" or "weekly" — whichever AppSettings.fleet_summary_frequency
    # was in effect when this one was generated (kept even if the setting
    # is later changed, so old rows still show what cadence produced them).
    frequency: Mapped[str] = mapped_column(String(16), nullable=False)

    # The model's own plain-text/markdown-ish response — rendered on the
    # Dashboard through the same `| safe`-free Jinja escaping as any other
    # user-facing text in this app (a model's output is untrusted content,
    # same as SSH command output elsewhere).
    content: Mapped[str] = mapped_column(Text, nullable=False)

    # Which provider/model actually wrote it — display-only ("Generated by
    # anthropic/claude-...") and useful context if a model's phrasing looks
    # off after an admin changes the configured one.
    provider_kind: Mapped[str] = mapped_column(String(32), nullable=False)
    model_id: Mapped[str] = mapped_column(String(255), nullable=False)

    created_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        return f"FleetSummary(id={self.id!r}, frequency={self.frequency!r})"
